### ISSUE TITLE
Whole body pose estimation

### ISSUE THREAD

**Issue by akamob** [xkunwu/depth-hand#10]
Hi, Thank you for the great work.

I appreciate your work. I'm wondering if it is possible that use your code for whole body pose estimation? Could you please give me some suggestions?

Any help is much appreciated.
Thank you!

**Comment by xkunwu** [comment]
They are basically the same category, so in theory, yes. Body pose estimation in general requires fewer joints, so I would expect it runs faster. The resolution demands are also easier to satisfy than hand, so it should produce higher precision detections. But you should have better quality depth camera, as most of their performance are bad away from even 2 meters.
