### ISSUE TITLE
Problem in Running the train.evaluate

### ISSUE THREAD

**Issue by SQFeng01** [xkunwu/depth-hand#3]
It is said that the required data will be prepared automatically in your README, but when I run with that command it raised error in 'holder.py'
`FileNotFoundError: [Errno 2] No such file or directory: './data/hands17/training/Training_Annotation.txt'`
I wonder if I set directory incorrectly or made some other mistakes. Thanks.

**Comment by xkunwu** [comment]
For training, data files should be placed in "./data" directory (or elsewhere and specify a parameter). The main result is tested on 'Hands17' data, but I am not authorized to redistribute. Please contact the original authors for it.
