### ISSUE TITLE
running on live camera

### ISSUE THREAD

**Issue by ankurhanda** [xkunwu/depth-hand#5]
Is there any simple example which shows how to run the code for depth images coming from a live camera. something like 

```
img = camera.get_image()

out = network.run(img)

display(out)
```

I tried to look into it but I can't find such an example easily.

**Comment by ankurhanda** [comment]
Also, where can I find the `model.ckpt.meta` - is there any pretrained model? I looked into running `camera.capture` python script to see if I can get it running live on my realsense camera but I don't find the pre-trained model anywhere...

**Comment by ankurhanda** [comment]
`rsync-proj.sh` didn't work for me properly. How do you run `rsync-proj.sh` file? it seems to need arguments etc. Can you give an example please?

**Comment by xkunwu** [comment]
Hi,

- please read both "README" for estimation and detection first.
- camera.capture contains capture code.
- pretrained model can be downloaded, and instructions are in the "README".
- you can ignore rsync-proj.sh.
