### ISSUE TITLE
Pretrained model and/or data not downloadable

### ISSUE THREAD

**Issue by kowac** [xkunwu/depth-hand#7]
Hi everyone, hi Kelvin,

as suggested in your quick start guide I tried to download the pretrained model from your provided linked. Sadly, I was not able to obtain said data due to the fact that I have to register on the platform, which is not possible. Do you know of any other possibilities to get the pretrained model and/or data?
Thank you in advance.

Best regards,
Chris

**Comment by xkunwu** [comment]
Thanks for checking the link. There are other ways to access that platform without using their app (and even higher download speed), but it might be a pain if you have no interest in that storage provider.

Then you need to read more than the "quick start". All information about resource is documented in the following section of the main repo:
https://github.com/xkunwu/depth-hand/tree/master/code#resources

From there, you can find a Google drive download link, and more information about almost everything.

**Comment by kowac** [comment]
Oh, seems like I just overlooked this one. Thanks alot!
