### ISSUE TITLE
Cannot run camera.capture

### ISSUE THREAD

**Issue by HungDuong1998** [xkunwu/depth-hand#9]
Hi, I was trying to reproduce the detection result for my project using you pretrained model, but as i run

python3 -m camera.capture \
    --data_root=$HOME/data \
    --out_root=$HOME/data/univue/output \
    --model_name=super_edt2m

The program tries to find Training_Annotation.txt 

Here's the error log

2021-08-23 10:46:54.388726: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.10.2
21-08-23 10:46:59 [INFO ]  ######## hands17 [super_edt2m] ########
21-08-23 10:46:59 [INFO ]  cleaning data ...
Traceback (most recent call last):
  File "/home/hungduong/Downloads/depth-hand/code/camera/capture.py", line 363, in <module>
    if not argsholder.create_instance():
  File "/home/hungduong/Downloads/depth-hand/code/args_holder.py", line 399, in create_instance
    self.args.data_inst.init_data()
  File "/home/hungduong/Downloads/depth-hand/code/data/hands17/holder.py", line 286, in init_data
    pose_limit = self.remove_out_frame_annot_mt()
  File "/home/hungduong/Downloads/depth-hand/code/data/hands17/holder.py", line 197, in remove_out_frame_annot_mt
    reader = filepack.push_file(self.training_annot_origin)
  File "/home/hungduong/Downloads/depth-hand/code/utils/coder.py", line 50, in push_file
    file = open(name, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/hungduong/data/hands17/training/Training_Annotation.txt'

Can you help check again? I'm using nvidia jetson nano realsense D435i and python3 virtualenv as conda cannot be installed on jetson yet.

Thanks

**Comment by xkunwu** [comment]
The log shows that you do not have the pretrained model yet, so the code will try to train a new model from the raw training data. You can find the downloading links for the pretrained model in “README.md”, or put the raw data into correct path if you have it and would like to train your own model.

Cheers.

**Comment by HungDuong1998** [comment]
I have downloaded the pretrained model, symlinked as instructed.
After further inspection and try commenting out this line of code in args_holder.py, the program ran successfully.
Is it a bug?

![image](https://user-images.githubusercontent.com/87010829/130723090-7738ec50-9645-4395-bec6-037d113f7ad4.png)
(line 399 -> self.args.data_inst.init_data())

Anyway, it works but the performance on the nano seemed to be slow (delayed and low in fps) and the hand of depth image quality is not really good as I move further from the camera. 

Is there any way to improve the performance and image input quality?

Many thanks.
